name: Convert incoming Figma tokens to variables

on:
  push:
    branches: [main]

# Sets permissions to allow commiting to the repository
permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  convert-and-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run convertor
        run: npm run convert-all

      - name: Commit and push if changes
        run: |
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add -A
          git commit -m "Generated build output" -a || exit 0 # This line prevents the action from failing if there's nothing to commit
          git push

      - name: Notify Slack about the update
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "✅ Design Tokens updated!"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ github.event.head_commit.message }}"
                  }
                }
              ]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
